#! /bin/sh
### BEGIN INIT INFO
# Provides: redis-server
# Short-Description: redis-server - Persistent key-value db
# Description: redis-server - Persistent key-value db
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/redis/src/redis-server
DAEMON_ARGS=/usr/local/redis/redis.conf
NAME=redis-server
DESC=redis-server
 
RUNDIR=/usr/local/redis
PIDFILE=$RUNDIR/redis-server.pid
 
test -x $DAEMON || exit 0

set -e
 
case "$1" in
start)
	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		PROC=`cat $PIDFILE`
		echo "$NAME running exists pid $PROC; process is already running or crashed"
		exit 1
	fi
	echo -n "Starting $DESC: "
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown root:root $RUNDIR $PIDFILE
	chmod 755 $RUNDIR
	
	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid root:root --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME"
	else
		echo "failed"
	fi
	;;
stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;
 
restart|force-reload)
	${0} stop
	${0} start
	;;
 
status)
	echo -n "$DESC is "
	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		PROC=`cat $PIDFILE`
		echo "running pid $PROC"
	else
		echo "not running"
		exit 1
	fi
	;;
 
*)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac
 
exit 0
